/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.RegistroProducto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author nearQ
 */
public class Form_gestionarProducto extends javax.swing.JFrame {
    private String nombre;
    /**
     * Creates new form Form_gestionarProducto
     */
    public Form_gestionarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jtxt_telefono2 = new javax.swing.JTextField();
        jtxt_nombre2 = new javax.swing.JTextField();
        jtxt_dvRazonSocial2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtxt_razonSocial2 = new javax.swing.JTextField();
        jtxt_mail2 = new javax.swing.JTextField();
        jtxt_direccion2 = new javax.swing.JTextField();
        jbtn_salir2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcmbo_comuna2 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jbtn_borrar2 = new javax.swing.JButton();
        jbtn_guardar2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jcmbo_region2 = new javax.swing.JComboBox<>();
        jcmbo_provincia2 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbl_proveedor4 = new javax.swing.JTable();
        jbtn_listar4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jbtn_eliminar1 = new javax.swing.JButton();
        jtxt_nombreProv1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtbl_proveedor5 = new javax.swing.JTable();
        jbtn_listar5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTbP_agregarProducto = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jbtn_listar2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtbl_productos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jbtn_eliminar = new javax.swing.JButton();
        jtxt_nombreProd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbl_productos1 = new javax.swing.JTable();
        jbtn_listar3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtn_salir1 = new javax.swing.JButton();
        jbtn_borrar1 = new javax.swing.JButton();
        jbtn_guardar1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jtxt_codProveedor = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jtxt_stock = new javax.swing.JTextField();
        jtxt_descripcion = new javax.swing.JTextField();
        jtxt_porcentajeDescuento = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_codCategoria = new javax.swing.JTextField();
        jtxt_codigo = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jtxt_codigo1 = new javax.swing.JTextField();
        jtxt_codCategoria1 = new javax.swing.JTextField();
        jtxt_codProveedor1 = new javax.swing.JTextField();
        jtxt_precio1 = new javax.swing.JTextField();
        jtxt_stock1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jtxt_descripcion1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jbtn_guardarCambios = new javax.swing.JButton();
        jtxt_porcentajeDescuento1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jbtn_salir3 = new javax.swing.JButton();
        jbtn_borrarCambios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxt_nombreBuscar = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setTitle("Agregar Empleado");

        jTabbedPane6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setText("Telefono:");

        jtxt_telefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_telefono2ActionPerformed(evt);
            }
        });

        jtxt_dvRazonSocial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_dvRazonSocial2ActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre:");

        jtxt_direccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_direccion2ActionPerformed(evt);
            }
        });

        jbtn_salir2.setText("Salir");
        jbtn_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir2ActionPerformed(evt);
            }
        });

        jLabel27.setText("Dirección:");

        jLabel28.setText("Email:");

        jLabel29.setText("-");

        jcmbo_comuna2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Santiago", "Viña del Mar", "Quilpué" }));

        jLabel30.setText("Comuna:");

        jbtn_borrar2.setText("Borrar cambios");
        jbtn_borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrar2ActionPerformed(evt);
            }
        });

        jbtn_guardar2.setText("Guardar cambios");
        jbtn_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardar2ActionPerformed(evt);
            }
        });

        jLabel31.setText("Región:");

        jLabel32.setText("Provincia:");

        jLabel33.setText("Razon social:");

        jcmbo_region2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "RM", "Arica", "Maule" }));

        jcmbo_provincia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "Marga-marga", "Talca", "Putre", "Limache", "Santiago" }));
        jcmbo_provincia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbo_provincia2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel28))
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jtxt_mail2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcmbo_region2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxt_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(19, 19, 19)
                                        .addComponent(jtxt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_razonSocial2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jtxt_dvRazonSocial2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(393, 393, 393))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(117, 117, 117))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcmbo_comuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcmbo_provincia2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jbtn_guardar2)
                                .addGap(96, 96, 96)
                                .addComponent(jbtn_borrar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_salir2)
                                .addGap(172, 172, 172))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jtxt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jtxt_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_razonSocial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel29)
                            .addComponent(jtxt_dvRazonSocial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jtxt_mail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jcmbo_comuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jcmbo_region2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbo_provincia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardar2)
                    .addComponent(jbtn_borrar2)
                    .addComponent(jbtn_salir2))
                .addGap(42, 42, 42))
        );

        jTabbedPane6.addTab("Agregar Proveedor", jPanel6);

        jtbl_proveedor4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razon Social", "Dv Razon", "Nombre", "Email", "Direccion", "Region", "Provincia", "Comuna", "Telefono"
            }
        ));
        jScrollPane6.setViewportView(jtbl_proveedor4);

        jbtn_listar4.setText("Listar");
        jbtn_listar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_listar4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_listar4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jTabbedPane6.addTab("Lista Proveedores", jPanel8);

        jbtn_eliminar1.setText("Eliminar");
        jbtn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminar1ActionPerformed(evt);
            }
        });

        jLabel34.setText("Nombre Proveedor:");

        jtbl_proveedor5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razon Social", "Dv Razon", "Nombre", "Email", "Direccion", "Region", "Provincia", "Comuna", "Telefono"
            }
        ));
        jScrollPane7.setViewportView(jtbl_proveedor5);

        jbtn_listar5.setText("Listar");
        jbtn_listar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jbtn_listar5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jtxt_nombreProv1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtn_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
            .addComponent(jScrollPane7)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jtxt_nombreProv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_listar5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTabbedPane6.addTab("Eliminar Proveedor", jPanel9);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gestionar proveedores");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Productos");

        jTbP_agregarProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtn_listar2.setText("Listar");
        jbtn_listar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listar2ActionPerformed(evt);
            }
        });

        jtbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "stock", "Categoria ", "Cod Proveedor", "Descuento"
            }
        ));
        jScrollPane8.setViewportView(jtbl_productos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jbtn_listar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_listar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTbP_agregarProducto.addTab("Lista de productos", jPanel5);

        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre Producto:");

        jtbl_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "stock", "Categoria ", "Cod Proveedor", "Descuento"
            }
        ));
        jScrollPane5.setViewportView(jtbl_productos1);

        jbtn_listar3.setText("Listar");
        jbtn_listar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbtn_listar3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxt_nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_listar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTbP_agregarProducto.addTab("Eliminar Productos", jPanel7);

        jbtn_salir1.setText("Salir");
        jbtn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir1ActionPerformed(evt);
            }
        });

        jbtn_borrar1.setText("Borrar cambios");
        jbtn_borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrar1ActionPerformed(evt);
            }
        });

        jbtn_guardar1.setText("Guardar cambios");
        jbtn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardar1ActionPerformed(evt);
            }
        });

        jLabel36.setText("Codigo:");

        jLabel35.setText("Stock:");

        jLabel38.setText("Descuento:");

        jLabel39.setText("Codigo proveedor:");

        jLabel37.setText("Nombre:");

        jLabel40.setText("Codigo categoria:");

        jLabel3.setText("Precio:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbtn_guardar1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(27, 27, 27)
                        .addComponent(jtxt_porcentajeDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_codProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jbtn_borrar1)
                .addGap(64, 64, 64)
                .addComponent(jbtn_salir1)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_porcentajeDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardar1)
                    .addComponent(jbtn_borrar1)
                    .addComponent(jbtn_salir1))
                .addGap(31, 31, 31))
        );

        jTbP_agregarProducto.addTab("Agregar Productos", jPanel4);

        jtxt_codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_codigo1ActionPerformed(evt);
            }
        });

        jLabel41.setText("Codigo categoria:");

        jLabel42.setText("Stock:");

        jLabel7.setText("Precio:");

        jLabel43.setText("Codigo:");

        jtxt_descripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_descripcion1ActionPerformed(evt);
            }
        });

        jLabel44.setText("Nombre:");

        jbtn_guardarCambios.setText("Actualizar");
        jbtn_guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarCambiosActionPerformed(evt);
            }
        });

        jLabel45.setText("Descuento:");

        jLabel46.setText("Codigo proveedor:");

        jbtn_salir3.setText("Salir");
        jbtn_salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir3ActionPerformed(evt);
            }
        });

        jbtn_borrarCambios.setText("Borrar cambios");
        jbtn_borrarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarCambiosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre a buscar:");

        jtxt_nombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreBuscarActionPerformed(evt);
            }
        });

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_precio1)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jtxt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel45)
                                    .addGap(21, 21, 21)
                                    .addComponent(jtxt_porcentajeDescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxt_codProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_codCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jbtn_guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jtxt_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jbtn_buscar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jbtn_borrarCambios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_salir3)
                                .addGap(16, 16, 16)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_buscar)
                    .addComponent(jtxt_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))))
                .addGap(4, 4, 4)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_precio1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_codProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jtxt_porcentajeDescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardarCambios)
                    .addComponent(jbtn_borrarCambios)
                    .addComponent(jbtn_salir3))
                .addGap(31, 31, 31))
        );

        jTbP_agregarProducto.addTab("Modificar Producto", jPanel10);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Gestionar productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jTbP_agregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTbP_agregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_listar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listar2ActionPerformed

        int precioUnitario,stock,codCategoria,numRazonSocialProv;
        double porcentajeDescuento;
        String descripcionProducto, codProducto;
        
        RegistroProducto rp = new RegistroProducto();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_productos.getModel();
        modelo.setRowCount(0);
        List<Producto> lista = rp.buscarTodos();
        
        for (Producto producto : lista) {
            codProducto = producto.getCodProducto();
            descripcionProducto = producto.getDescripcionProducto();
            precioUnitario = producto.getPrecioUnitario();
            stock = producto.getStock();
            codCategoria  = producto.getCodigoCategoria();
            numRazonSocialProv = producto.getNumRazonSocialProv();
            porcentajeDescuento = producto.getPorcentajeDescuento();
            
            modelo.addRow(new Object[]{codProducto,descripcionProducto,precioUnitario,stock,codCategoria,numRazonSocialProv,porcentajeDescuento});
            
        }
    }//GEN-LAST:event_jbtn_listar2ActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        String nombre_eliminar = this.jtxt_nombreProd.getText();
        RegistroProducto rp = new RegistroProducto();
        if (rp.eliminarProducto(nombre_eliminar)) {
            
           JOptionPane.showMessageDialog(null,"Producto Eliminado","Eliminar producto",1);         
        }
        else{
           JOptionPane.showMessageDialog(null,"Producto no Eliminado","Eliminar producto",0);  
        }
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_listar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listar3ActionPerformed
        int precioUnitario,stock,codCategoria,numRazonSocialProv;
        double porcentajeDescuento;
        String descripcionProducto, codProducto;
        
        RegistroProducto rp = new RegistroProducto();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_productos1.getModel();
        modelo.setRowCount(0);
        List<Producto> lista = rp.buscarTodos();
        
        for (Producto producto : lista) {
            codProducto = producto.getCodProducto();
            descripcionProducto = producto.getDescripcionProducto();
            precioUnitario = producto.getPrecioUnitario();
            stock = producto.getStock();
            codCategoria  = producto.getCodigoCategoria();
            numRazonSocialProv = producto.getNumRazonSocialProv();
            porcentajeDescuento = producto.getPorcentajeDescuento();
            
            modelo.addRow(new Object[]{codProducto,descripcionProducto,precioUnitario,stock,codCategoria,numRazonSocialProv,porcentajeDescuento});
            
        }
    }//GEN-LAST:event_jbtn_listar3ActionPerformed

    private void jtxt_telefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_telefono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefono2ActionPerformed

    private void jtxt_dvRazonSocial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_dvRazonSocial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_dvRazonSocial2ActionPerformed

    private void jtxt_direccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_direccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_direccion2ActionPerformed

    private void jbtn_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir2ActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir2ActionPerformed

    private void jbtn_borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrar2ActionPerformed


    }//GEN-LAST:event_jbtn_borrar2ActionPerformed

    private void jbtn_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardar2ActionPerformed

    }//GEN-LAST:event_jbtn_guardar2ActionPerformed

    private void jcmbo_provincia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbo_provincia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbo_provincia2ActionPerformed

    private void jbtn_listar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listar4ActionPerformed

    }//GEN-LAST:event_jbtn_listar4ActionPerformed

    private void jbtn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminar1ActionPerformed

    }//GEN-LAST:event_jbtn_eliminar1ActionPerformed

    private void jbtn_listar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listar5ActionPerformed

    }//GEN-LAST:event_jbtn_listar5ActionPerformed

    private void jbtn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardar1ActionPerformed
        RegistroProducto regProd = new RegistroProducto();
        String codProducto = ((jtxt_codigo.getText()));
        String descripcionProducto = (jtxt_descripcion.getText());
        int precioUnitario = ((Integer.valueOf(jtxt_precio.getText())));
        int stock = ((Integer.valueOf(jtxt_stock.getText())));
        int codCategoria = ((Integer.valueOf(jtxt_codCategoria.getText())));
        int numRazonSocialProv = ((Integer.valueOf(jtxt_codProveedor.getText())));
        double porcentajeDescuento = ((Double.valueOf(jtxt_porcentajeDescuento.getText())));
        Producto prod = new Producto(codProducto, precioUnitario, stock, codCategoria, numRazonSocialProv, porcentajeDescuento, descripcionProducto);
        if (regProd.agregarProducto(prod)) {
            JOptionPane.showMessageDialog(null,"Producto ingresado","Ingresar Producto",1);
        }
        else{
            JOptionPane.showMessageDialog(null,"Producto No ingresado","Ingresar Producto",0);
        }
    }//GEN-LAST:event_jbtn_guardar1ActionPerformed

    private void jbtn_borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrar1ActionPerformed
        this.jtxt_codigo.setText("");
        this.jtxt_descripcion.setText("");
        this.jtxt_precio.setText("");
        this.jtxt_stock.setText("");
        this.jtxt_codCategoria.setText("");
        this.jtxt_codProveedor.setText("");
        this.jtxt_porcentajeDescuento.setText("");
    }//GEN-LAST:event_jbtn_borrar1ActionPerformed

    private void jbtn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir1ActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir1ActionPerformed

    private void jbtn_guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarCambiosActionPerformed
        RegistroProducto rp = new RegistroProducto();
        Producto pr = new Producto();       
        pr.setCodProducto((this.jtxt_codigo1.getText()));
        pr.setDescripcionProducto(this.jtxt_descripcion1.getText());
        pr.setPrecioUnitario((Integer.valueOf(this.jtxt_precio1.getText())));
        pr.setStock((Integer.valueOf(this.jtxt_stock1.getText())));
        pr.setCodigoCategoria((Integer.valueOf(this.jtxt_codCategoria1.getText())));
        pr.setNumRazonSocialProv((Integer.valueOf(this.jtxt_codProveedor1.getText())));
        pr.setPorcentajeDescuento((Double.valueOf(this.jtxt_porcentajeDescuento1.getText())));
        if (rp.actualizarProducto(pr,jtxt_nombreBuscar.getText())) {
            JOptionPane.showMessageDialog(null,"Producto Actualizado","Actualizar producto",1);
            System.out.println(pr.toString());
        }
        else{
            JOptionPane.showMessageDialog(null,"Producto No Actualizado","Actualizar producto",0);
        }
        
    }//GEN-LAST:event_jbtn_guardarCambiosActionPerformed

    private void jbtn_salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir3ActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir3ActionPerformed

    private void jbtn_borrarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarCambiosActionPerformed
        this.jtxt_codigo1.setText("");
        this.jtxt_descripcion1.setText("");
        this.jtxt_precio1.setText("");
        this.jtxt_stock1.setText("");
        this.jtxt_codCategoria1.setText("");
        this.jtxt_codProveedor1.setText("");
        this.jtxt_porcentajeDescuento1.setText("");
    }//GEN-LAST:event_jbtn_borrarCambiosActionPerformed

    private void jtxt_nombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreBuscarActionPerformed

    }//GEN-LAST:event_jtxt_nombreBuscarActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        nombre = this.jtxt_nombreBuscar.getText();
        RegistroProducto rp = new RegistroProducto();
        Producto pr = rp.buscarPorNombre(nombre);
        this.jtxt_descripcion1.setText(pr.getDescripcionProducto());
        this.jtxt_codigo1.setText(String.valueOf(pr.getCodProducto()));
        this.jtxt_precio1.setText(String.valueOf(pr.getPrecioUnitario()));
        this.jtxt_stock1.setText(String.valueOf(pr.getStock()));
        this.jtxt_codCategoria1.setText(String.valueOf(pr.getCodigoCategoria()));
        this.jtxt_codProveedor1.setText(String.valueOf(pr.getNumRazonSocialProv()));
        this.jtxt_porcentajeDescuento1.setText(String.valueOf(pr.getPorcentajeDescuento()));
        
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jtxt_descripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_descripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_descripcion1ActionPerformed

    private void jtxt_codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_codigo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_gestionarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTbP_agregarProducto;
    private javax.swing.JButton jbtn_borrar1;
    private javax.swing.JButton jbtn_borrar2;
    private javax.swing.JButton jbtn_borrarCambios;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_eliminar1;
    private javax.swing.JButton jbtn_guardar1;
    private javax.swing.JButton jbtn_guardar2;
    private javax.swing.JButton jbtn_guardarCambios;
    private javax.swing.JButton jbtn_listar2;
    private javax.swing.JButton jbtn_listar3;
    private javax.swing.JButton jbtn_listar4;
    private javax.swing.JButton jbtn_listar5;
    private javax.swing.JButton jbtn_salir1;
    private javax.swing.JButton jbtn_salir2;
    private javax.swing.JButton jbtn_salir3;
    private javax.swing.JComboBox<String> jcmbo_comuna2;
    private javax.swing.JComboBox<String> jcmbo_provincia2;
    private javax.swing.JComboBox<String> jcmbo_region2;
    private javax.swing.JTable jtbl_productos;
    private javax.swing.JTable jtbl_productos1;
    private javax.swing.JTable jtbl_proveedor4;
    private javax.swing.JTable jtbl_proveedor5;
    private javax.swing.JTextField jtxt_codCategoria;
    private javax.swing.JTextField jtxt_codCategoria1;
    private javax.swing.JTextField jtxt_codProveedor;
    private javax.swing.JTextField jtxt_codProveedor1;
    private javax.swing.JTextField jtxt_codigo;
    private javax.swing.JTextField jtxt_codigo1;
    private javax.swing.JTextField jtxt_descripcion;
    private javax.swing.JTextField jtxt_descripcion1;
    private javax.swing.JTextField jtxt_direccion2;
    private javax.swing.JTextField jtxt_dvRazonSocial2;
    private javax.swing.JTextField jtxt_mail2;
    private javax.swing.JTextField jtxt_nombre2;
    private javax.swing.JTextField jtxt_nombreBuscar;
    private javax.swing.JTextField jtxt_nombreProd;
    private javax.swing.JTextField jtxt_nombreProv1;
    private javax.swing.JTextField jtxt_porcentajeDescuento;
    private javax.swing.JTextField jtxt_porcentajeDescuento1;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_precio1;
    private javax.swing.JTextField jtxt_razonSocial2;
    private javax.swing.JTextField jtxt_stock;
    private javax.swing.JTextField jtxt_stock1;
    private javax.swing.JTextField jtxt_telefono2;
    // End of variables declaration//GEN-END:variables
}
