/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Gabriel Serrano
 */
import controlador.RegistroEmpleado;
import java.time.LocalDate;
import java.util.Date;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

public class Form_gestionarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Form_gestionarEmpleado
     */
    public Form_gestionarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtn_vistaAgregar = new javax.swing.JButton();
        jbtn_vistaModificar = new javax.swing.JButton();
        jbtn_vistaBuscar = new javax.swing.JButton();
        jbtn_vistaEliminar = new javax.swing.JButton();
        jtabPane_gestionarEmpleado = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcmbo_region = new javax.swing.JComboBox<>();
        jcmbo_provincia = new javax.swing.JComboBox<>();
        jcmbo_comuna = new javax.swing.JComboBox<>();
        jdate_fecNac = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxt_aPaterno = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_aMaterno = new javax.swing.JTextField();
        jtxt_numRut = new javax.swing.JTextField();
        jtxt_mail = new javax.swing.JTextField();
        jtxt_celular = new javax.swing.JTextField();
        jtxt_usuario = new javax.swing.JTextField();
        jtxt_dvRut = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jtxt_direccion = new javax.swing.JTextField();
        jtxt_contraseña = new javax.swing.JPasswordField();
        jchk_mostraContra = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jcmbo_rol = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jcmbo_region2 = new javax.swing.JComboBox<>();
        jcmbo_provincia2 = new javax.swing.JComboBox<>();
        jcmbo_comuna2 = new javax.swing.JComboBox<>();
        jdate_fecNac2 = new com.toedter.calendar.JDateChooser();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jtxt_aPaterno2 = new javax.swing.JTextField();
        jtxt_nombre2 = new javax.swing.JTextField();
        jtxt_aMaterno2 = new javax.swing.JTextField();
        jtxt_numRut2 = new javax.swing.JTextField();
        jtxt_mail2 = new javax.swing.JTextField();
        jtxt_celular2 = new javax.swing.JTextField();
        jtxt_usuario2 = new javax.swing.JTextField();
        jtxt_dvRut2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jbtn_guardar2 = new javax.swing.JButton();
        jbtn_borrar2 = new javax.swing.JButton();
        jbtn_salir2 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jtxt_direccion2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jtxt_rutBuscado = new javax.swing.JTextField();
        jbtn_buscarRut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jtxt_contraseña2 = new javax.swing.JPasswordField();
        jchk_mostraContra1 = new javax.swing.JCheckBox();
        jcmbo_rol2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jtxt_busqueda = new javax.swing.JTextField();
        jrad_rut = new javax.swing.JRadioButton();
        jrad_rol = new javax.swing.JRadioButton();
        jbttn_buscarFiltro = new javax.swing.JButton();
        jrad_todos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_busquedaFiltro = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jbtn_buscarRut1 = new javax.swing.JButton();
        jtxt_rutBuscado2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_busquedaResultado = new javax.swing.JTable();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_salir3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Empleados");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Gestionar empleados");

        jbtn_vistaAgregar.setText("Agregar empleado");
        jbtn_vistaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_vistaAgregarActionPerformed(evt);
            }
        });

        jbtn_vistaModificar.setText("Modificar empleado");
        jbtn_vistaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_vistaModificarActionPerformed(evt);
            }
        });

        jbtn_vistaBuscar.setText("Buscar empleados");
        jbtn_vistaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_vistaBuscarActionPerformed(evt);
            }
        });

        jbtn_vistaEliminar.setText("Eliminar empleado");
        jbtn_vistaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_vistaEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(322, 322, 322))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jbtn_vistaAgregar)
                .addGap(53, 53, 53)
                .addComponent(jbtn_vistaModificar)
                .addGap(52, 52, 52)
                .addComponent(jbtn_vistaBuscar)
                .addGap(42, 42, 42)
                .addComponent(jbtn_vistaEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_vistaAgregar)
                    .addComponent(jbtn_vistaModificar)
                    .addComponent(jbtn_vistaBuscar)
                    .addComponent(jbtn_vistaEliminar))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Usuario:");

        jLabel5.setText("Rut:");

        jLabel6.setText("Email:");

        jLabel7.setText("Apellido materno:");

        jLabel8.setText("Apellido paterno:");

        jLabel9.setText("Celular:");

        jLabel10.setText("Fecha de nacimiento:");

        jLabel11.setText("Comuna:");

        jLabel12.setText("Provincia:");

        jLabel13.setText("Región:");

        jcmbo_region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "RM", "Arica", "Maule" }));

        jcmbo_provincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "Marga-marga", "Talca", "Putre", "Limache", "Santiago" }));

        jcmbo_comuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Santiago", "Viña del Mar", "Quilpué" }));

        jLabel14.setText("Nombre:");

        jLabel15.setText("Contraseña:");

        jtxt_dvRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_dvRutActionPerformed(evt);
            }
        });

        jLabel16.setText("-");

        jbtn_guardar.setText("Guardar cambios");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        jbtn_borrar.setText("Borrar cambios");
        jbtn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarActionPerformed(evt);
            }
        });

        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        jLabel17.setText("Dirección");

        jtxt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_contraseñaActionPerformed(evt);
            }
        });

        jchk_mostraContra.setText("Mostrar contraseña");
        jchk_mostraContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_mostraContraActionPerformed(evt);
            }
        });

        jLabel18.setText("Rol:");

        jcmbo_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Cajero" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(548, 548, 548))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jcmbo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdate_fecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtn_guardar)
                                            .addComponent(jtxt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcmbo_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_aPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_numRut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_dvRut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jbtn_borrar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtn_salir))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jcmbo_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcmbo_region, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchk_mostraContra)
                                            .addComponent(jtxt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxt_aPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_numRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_dvRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_fecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(jtxt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jcmbo_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jcmbo_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbo_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbo_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(jtxt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jchk_mostraContra)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardar)
                    .addComponent(jbtn_borrar)
                    .addComponent(jbtn_salir))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jtabPane_gestionarEmpleado.addTab("Agregar empleado", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel32.setText("Usuario:");

        jLabel33.setText("Rut:");

        jLabel34.setText("Email:");

        jLabel35.setText("Apellido materno:");

        jLabel36.setText("Apellido paterno:");

        jLabel37.setText("Celular:");

        jLabel38.setText("Fecha de nacimiento:");

        jLabel39.setText("Comuna:");

        jLabel40.setText("Provincia:");

        jLabel41.setText("Región:");

        jcmbo_region2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "RM", "Arica", "Maule" }));

        jcmbo_provincia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Valparaíso", "Marga-marga", "Talca", "Putre", "Limache", "Santiago" }));

        jcmbo_comuna2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Santiago", "Viña del Mar", "Quilpué" }));

        jLabel42.setText("Nombre:");

        jLabel43.setText("Contraseña");

        jtxt_dvRut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_dvRut2ActionPerformed(evt);
            }
        });

        jLabel44.setText("-");

        jbtn_guardar2.setText("Guardar cambios");
        jbtn_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardar2ActionPerformed(evt);
            }
        });

        jbtn_borrar2.setText("Borrar cambios");
        jbtn_borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrar2ActionPerformed(evt);
            }
        });

        jbtn_salir2.setText("Salir");
        jbtn_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir2ActionPerformed(evt);
            }
        });

        jLabel45.setText("Dirección");

        jLabel47.setText("RUT empleado:");

        jbtn_buscarRut.setText("Buscar");
        jbtn_buscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarRutActionPerformed(evt);
            }
        });

        jtxt_contraseña2.setToolTipText("");

        jchk_mostraContra1.setText("Mostrar contraseña");
        jchk_mostraContra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_mostraContra1ActionPerformed(evt);
            }
        });

        jcmbo_rol2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Cajero" }));
        jcmbo_rol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbo_rol2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Rol:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(548, 548, 548))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jcmbo_comuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel39))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel40))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_rutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jbtn_buscarRut)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxt_celular2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdate_fecNac2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_aMaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtn_guardar2)
                                            .addComponent(jtxt_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcmbo_rol2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel43)
                                            .addGap(40, 40, 40)
                                            .addComponent(jtxt_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jchk_mostraContra1))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel34)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxt_mail2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel36)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxt_aPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxt_numRut2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_dvRut2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jbtn_borrar2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbtn_salir2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                                .addComponent(jcmbo_provincia2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel41)
                                                .addGap(18, 18, 18)
                                                .addComponent(jcmbo_region2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jtxt_rutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarRut))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jtxt_aPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jtxt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33)
                    .addComponent(jtxt_aMaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_numRut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_dvRut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_fecNac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(jLabel38)
                        .addComponent(jtxt_mail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jcmbo_rol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(jtxt_celular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jtxt_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jcmbo_region2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbo_provincia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbo_comuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel43)
                    .addComponent(jtxt_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchk_mostraContra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardar2)
                    .addComponent(jbtn_borrar2)
                    .addComponent(jbtn_salir2))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 136, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jtabPane_gestionarEmpleado.addTab("Modificar empleado", jPanel5);

        jLabel20.setText("Buscador de empleados");

        buttonGroup1.add(jrad_rut);
        jrad_rut.setText("RUT");
        jrad_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrad_rutActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrad_rol);
        jrad_rol.setText("Rol");

        jbttn_buscarFiltro.setText("Buscar");
        jbttn_buscarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn_buscarFiltroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrad_todos);
        jrad_todos.setText("Todos");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtbl_busquedaFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "DV", "Nombre", "Apellido Paterno", "Apellido Materno", "Email", "Celular", "Fecha nacimiento", "Dirección", "Región", "Provincia", "Comuna", "Usuario", "Rol"
            }
        ));
        jScrollPane1.setViewportView(jtbl_busquedaFiltro);

        jScrollPane4.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttn_buscarFiltro)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jtxt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jrad_rut)
                                .addGap(18, 18, 18)
                                .addComponent(jrad_rol)
                                .addGap(18, 18, 18)
                                .addComponent(jrad_todos)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrad_rut)
                    .addComponent(jrad_rol)
                    .addComponent(jrad_todos))
                .addGap(18, 18, 18)
                .addComponent(jbttn_buscarFiltro)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        jtabPane_gestionarEmpleado.addTab("Buscar empleados", jPanel6);

        jbtn_buscarRut1.setText("Buscar");
        jbtn_buscarRut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarRut1ActionPerformed(evt);
            }
        });

        jtxt_rutBuscado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rutBuscado2ActionPerformed(evt);
            }
        });

        jLabel48.setText("RUT empleado:");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtbl_busquedaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "DV", "Nombre", "Apellido Paterno", "Apellido Materno", "Email", "Celular", "Fecha nacimiento", "Dirección", "Región", "Provincia", "Comuna", "Usuario", "Rol"
            }
        ));
        jtbl_busquedaResultado.setMinimumSize(new java.awt.Dimension(220, 0));
        jScrollPane3.setViewportView(jtbl_busquedaResultado);

        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_salir3.setText("Salir");
        jbtn_salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtn_eliminar)
                .addGap(114, 114, 114)
                .addComponent(jbtn_salir3)
                .addGap(385, 385, 385))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_rutBuscado2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jbtn_buscarRut1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jtxt_rutBuscado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarRut1))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_eliminar)
                    .addComponent(jbtn_salir3))
                .addGap(183, 183, 183))
        );

        jtabPane_gestionarEmpleado.addTab("Eliminar empleado", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtabPane_gestionarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtabPane_gestionarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_vistaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_vistaAgregarActionPerformed
        jtabPane_gestionarEmpleado.setSelectedIndex(0);
    }//GEN-LAST:event_jbtn_vistaAgregarActionPerformed

    private void jbtn_vistaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_vistaModificarActionPerformed
        jtabPane_gestionarEmpleado.setSelectedIndex(1);
    }//GEN-LAST:event_jbtn_vistaModificarActionPerformed

    private void jbtn_vistaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_vistaBuscarActionPerformed
        jtabPane_gestionarEmpleado.setSelectedIndex(2);
    }//GEN-LAST:event_jbtn_vistaBuscarActionPerformed

    private void jbtn_vistaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_vistaEliminarActionPerformed
        jtabPane_gestionarEmpleado.setSelectedIndex(3);
    }//GEN-LAST:event_jbtn_vistaEliminarActionPerformed

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void jbtn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarActionPerformed
        jtxt_numRut.setText("");
        jtxt_dvRut.setText("");
        jtxt_nombre.setText("");
        jtxt_aPaterno.setText("");
        jtxt_aMaterno.setText("");
        jtxt_mail.setText("");
        jtxt_celular.setText("");
        jdate_fecNac.setDate(null);
        jcmbo_comuna.setSelectedIndex(0);
        jcmbo_provincia.setSelectedIndex(0);
        jcmbo_region.setSelectedIndex(0);
        jtxt_direccion.setText("");
        jtxt_usuario.setText("");
        jcmbo_rol.setSelectedIndex(0);

    }//GEN-LAST:event_jbtn_borrarActionPerformed

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        Empleado empleado = new Empleado();
        int comuna = 0;
        int provincia = 0;
        int region = 0;
        int rol = 0;

        empleado.setNumRutEmpleado((Integer.valueOf(jtxt_numRut.getText())));
        empleado.setDvRutEmpleado(jtxt_dvRut.getText());
        empleado.setpNombreEmpleado(jtxt_nombre.getText());
        empleado.setpApellidoEmpleado(jtxt_aPaterno.getText());
        empleado.setsApellidoEmpleado(jtxt_aMaterno.getText());
        empleado.setEmailEmpleado(jtxt_mail.getText());
        empleado.setCelularEmpleado(Integer.valueOf(jtxt_celular.getText()));
        empleado.setFechaNacEmpleado(jdate_fecNac.getDate());
        empleado.setDireccionEmpleado(jtxt_direccion.getText());
        //Setea comuna segun código en la DB
        switch (String.valueOf(jcmbo_comuna.getSelectedItem())) {
            case "Viña del Mar":
                comuna = 100;
                break;
            case "Quilpué":
                comuna = 101;
                break;
            case "Santiago":
                comuna = 102;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodComuna(comuna);
        //Setea provincia segun código en la DB
        switch (String.valueOf(jcmbo_provincia.getSelectedItem())) {
            case "Valparaíso":
                provincia = 100;
                break;
            case "Marga-marga":
                provincia = 101;
                break;
            case "Talca":
                provincia = 103;
                break;
            case "Putre":
                provincia = 104;
                break;
            case "Limache":
                provincia = 106;
                break;
            case "Santiago":
                provincia = 107;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodProvincia(provincia);
        //Setea region segun código en la DB
        switch (String.valueOf(jcmbo_region.getSelectedItem())) {
            case "Valparaíso":
                region = 10;
                break;
            case "RM":
                region = 11;
                break;
            case "Arica":
                region = 12;
                break;
            case "Maule":
                region = 13;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodRegion(region);
        empleado.setDireccionEmpleado(jtxt_direccion.getText());
        empleado.setUsuarioEmpleado(jtxt_usuario.getText());
        empleado.setContrasenaEmpleado(jtxt_contraseña.getText());
        //Seleccionar, Administrador, Cajero
        switch (jcmbo_rol.getSelectedIndex()) {
            case 1:
                rol = 100;
                break;
            case 2:
                rol = 101;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodRol(rol);

        regEmp.agregarEmpleado(empleado);
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void jtxt_dvRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_dvRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_dvRutActionPerformed

    private void jtxt_dvRut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_dvRut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_dvRut2ActionPerformed

    private void jbtn_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardar2ActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        Empleado empleado = new Empleado();
        int comuna = 0;
        int provincia = 0;
        int region = 0;
        int rol = 0;

        empleado.setNumRutEmpleado((Integer.valueOf(jtxt_numRut2.getText())));
        empleado.setDvRutEmpleado(jtxt_dvRut2.getText());
        empleado.setpNombreEmpleado(jtxt_nombre2.getText());
        empleado.setpApellidoEmpleado(jtxt_aPaterno2.getText());
        empleado.setsApellidoEmpleado(jtxt_aMaterno2.getText());
        empleado.setEmailEmpleado(jtxt_mail2.getText());
        empleado.setCelularEmpleado(Integer.valueOf(jtxt_celular2.getText()));
        empleado.setFechaNacEmpleado(jdate_fecNac2.getDate());
        empleado.setDireccionEmpleado(jtxt_direccion2.getText());
        //Setea comuna segun código en la DB
        switch (String.valueOf(jcmbo_comuna2.getSelectedItem())) {
            case "Viña del Mar":
                comuna = 100;
                break;
            case "Quilpué":
                comuna = 101;
                break;
            case "Santiago":
                comuna = 102;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodComuna(comuna);
        //Setea provincia segun código en la DB
        switch (String.valueOf(jcmbo_provincia2.getSelectedItem())) {
            case "Valparaíso":
                provincia = 100;
                break;
            case "Marga-marga":
                provincia = 101;
                break;
            case "Talca":
                provincia = 103;
                break;
            case "Putre":
                provincia = 104;
                break;
            case "Limache":
                provincia = 106;
                break;
            case "Santiago":
                provincia = 107;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodProvincia(provincia);
        //Setea region segun código en la DB
        switch (String.valueOf(jcmbo_region2.getSelectedItem())) {
            case "Valparaíso":
                region = 10;
                break;
            case "RM":
                region = 11;
                break;
            case "Arica":
                region = 12;
                break;
            case "Maule":
                region = 13;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodRegion(region);
        empleado.setDireccionEmpleado(jtxt_direccion2.getText());
        empleado.setUsuarioEmpleado(jtxt_usuario2.getText());
        empleado.setContrasenaEmpleado(jtxt_contraseña2.getText());
        //Seleccionar, Administrador, Cajero
        switch (jcmbo_rol2.getSelectedIndex()) {
            case 1:
                rol = 100;
                break;
            case 2:
                rol = 101;
                break;
            default:
                throw new AssertionError();
        }
        empleado.setCodRol(rol);

        regEmp.actualizarEmpleado(empleado);
    }//GEN-LAST:event_jbtn_guardar2ActionPerformed

    private void jbtn_borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrar2ActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        String rut = jtxt_rutBuscado.getText();
        Empleado empleado = regEmp.buscarEmpleado(rut);
        int itemComuna = 0;
        int itemProvincia = 0;
        int itemRegion = 0;

        jtxt_numRut2.setText(String.valueOf(empleado.getNumRutEmpleado()));
        jtxt_dvRut2.setText(empleado.getDvRutEmpleado());
        jtxt_nombre2.setText(empleado.getpNombreEmpleado());
        jtxt_aPaterno2.setText(empleado.getpApellidoEmpleado());
        jtxt_aMaterno2.setText(empleado.getsApellidoEmpleado());
        jtxt_mail2.setText(empleado.getEmailEmpleado());
        jtxt_celular2.setText(String.valueOf(empleado.getCelularEmpleado()));
        jdate_fecNac2.setDate(empleado.getFechaNacEmpleado());

        switch (empleado.getCodComuna()) {
            case 100:
                itemComuna = 2;
                break;
            case 101:
                itemComuna = 3;
                break;
            case 102:
                itemComuna = 1;
                break;
            default:
                throw new AssertionError();
        }

        jcmbo_comuna2.setSelectedIndex(itemComuna);

        //Seleccionar, Valparaíso, Marga-marga, Talca, Putre, Limache, Santiago
        switch (empleado.getCodProvincia()) {
            case 100:
                itemProvincia = 1;
                break;
            case 101:
                itemProvincia = 2;
                break;
            case 103:
                itemProvincia = 3;
                break;
            case 104:
                itemProvincia = 4;
                break;
            case 106:
                itemProvincia = 5;
                break;
            case 107:
                itemProvincia = 6;
                break;
            default:
                throw new AssertionError();
        }

        jcmbo_provincia2.setSelectedIndex(itemProvincia);

        //Seleccionar, Valparaíso, RM, Arica, Maule
        switch (empleado.getCodRegion()) {
            case 10:
                itemRegion = 1;
                break;
            case 11:
                itemRegion = 2;
                break;
            case 12:
                itemRegion = 3;
                break;
            case 13:
                itemRegion = 4;
                break;
            default:
                throw new AssertionError();
        }
        jcmbo_region2.setSelectedIndex(itemRegion);

        jtxt_direccion2.setText(empleado.getDireccionEmpleado());
        jtxt_usuario2.setText(empleado.getUsuarioEmpleado());
        jtxt_contraseña2.setText(empleado.getContrasenaEmpleado());
        //Seleccionar, Administrador, Cajero
        switch (empleado.getCodRol()) {
            case 100:
                jcmbo_rol2.setSelectedIndex(1);
                break;
            case 2:
                jcmbo_rol2.setSelectedIndex(2);
                break;
            default:
                throw new AssertionError();
        }

    }//GEN-LAST:event_jbtn_borrar2ActionPerformed

    private void jbtn_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_salir2ActionPerformed

    private void jbtn_buscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarRutActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        String rut = jtxt_rutBuscado.getText();
        Empleado empleado = regEmp.buscarEmpleado(rut);
        int itemComuna = 0;
        int itemProvincia = 0;
        int itemRegion = 0;

        jtxt_numRut2.setText(String.valueOf(empleado.getNumRutEmpleado()));
        jtxt_dvRut2.setText(empleado.getDvRutEmpleado());
        jtxt_nombre2.setText(empleado.getpNombreEmpleado());
        jtxt_aPaterno2.setText(empleado.getpApellidoEmpleado());
        jtxt_aMaterno2.setText(empleado.getsApellidoEmpleado());
        jtxt_mail2.setText(empleado.getEmailEmpleado());
        jtxt_celular2.setText(String.valueOf(empleado.getCelularEmpleado()));
        jdate_fecNac2.setDate(empleado.getFechaNacEmpleado());

        switch (empleado.getCodComuna()) {
            case 100:
                itemComuna = 2;
                break;
            case 101:
                itemComuna = 3;
                break;
            case 102:
                itemComuna = 1;
                break;
            default:
                throw new AssertionError();
        }

        jcmbo_comuna2.setSelectedIndex(itemComuna);

        //Seleccionar, Valparaíso, Marga-marga, Talca, Putre, Limache, Santiago
        switch (empleado.getCodProvincia()) {
            case 100:
                itemProvincia = 1;
                break;
            case 101:
                itemProvincia = 2;
                break;
            case 103:
                itemProvincia = 3;
                break;
            case 104:
                itemProvincia = 4;
                break;
            case 106:
                itemProvincia = 5;
                break;
            case 107:
                itemProvincia = 6;
                break;
            default:
                throw new AssertionError();
        }

        jcmbo_provincia2.setSelectedIndex(itemProvincia);

        //Seleccionar, Valparaíso, RM, Arica, Maule
        switch (empleado.getCodRegion()) {
            case 10:
                itemRegion = 1;
                break;
            case 11:
                itemRegion = 2;
                break;
            case 12:
                itemRegion = 3;
                break;
            case 13:
                itemRegion = 4;
                break;
            default:
                throw new AssertionError();
        }
        jcmbo_region2.setSelectedIndex(itemRegion);

        jtxt_direccion2.setText(empleado.getDireccionEmpleado());
        jtxt_usuario2.setText(empleado.getUsuarioEmpleado());
        jtxt_contraseña2.setText(empleado.getContrasenaEmpleado());
        //Seleccionar, Administrador, Cajero
        switch (empleado.getCodRol()) {
            case 100:
                jcmbo_rol2.setSelectedIndex(1);
                break;
            case 101:
                jcmbo_rol2.setSelectedIndex(2);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jbtn_buscarRutActionPerformed

    private void jtxt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_contraseñaActionPerformed

    private void jchk_mostraContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_mostraContraActionPerformed
        if (jchk_mostraContra.isSelected()) {

            jtxt_contraseña.setEchoChar((char) 0);

        } else {
            jtxt_contraseña.setEchoChar('*');
        }

    }//GEN-LAST:event_jchk_mostraContraActionPerformed

    private void jchk_mostraContra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_mostraContra1ActionPerformed
        if (jchk_mostraContra1.isSelected()) {

            jtxt_contraseña2.setEchoChar((char) 0);

        } else {
            jtxt_contraseña2.setEchoChar('*');
        }
    }//GEN-LAST:event_jchk_mostraContra1ActionPerformed

    private void jcmbo_rol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbo_rol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbo_rol2ActionPerformed

    private void jrad_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrad_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrad_rutActionPerformed

    private void jbttn_buscarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn_buscarFiltroActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        String condicion = "";
        String txtBusqueda = jtxt_busqueda.getText();

        if (jrad_rut.isSelected()) {
            condicion = "numRutEmpleado";
        } else if (jrad_rol.isSelected()) {
            condicion = "codRol";
        }

        if (jrad_rol.isSelected()) {
            if (txtBusqueda.equalsIgnoreCase("administrador")) {
                txtBusqueda = "100";
            } else if (txtBusqueda.equalsIgnoreCase("cajero")) {
                txtBusqueda = "101";
            }
        }

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_busquedaFiltro.getModel();
        modelo.setRowCount(0);

        if (jrad_todos.isSelected()) {
            for (Empleado empleado : regEmp.buscarTodos()) {
                java.sql.Date dateSql = new java.sql.Date(empleado.getFechaNacEmpleado().getDay(), empleado.getFechaNacEmpleado().getMonth(), empleado.getFechaNacEmpleado().getYear());
                modelo.addRow(new Object[]{empleado.getNumRutEmpleado(),
                    empleado.getDvRutEmpleado(),
                    empleado.getpNombreEmpleado(),
                    empleado.getpApellidoEmpleado(),
                    empleado.getsApellidoEmpleado(),
                    empleado.getEmailEmpleado(),
                    empleado.getCelularEmpleado(),
                    dateSql,
                    empleado.getDireccionEmpleado(),
                    empleado.getCodComuna(),
                    empleado.getCodProvincia(),
                    empleado.getCodRegion(),
                    empleado.getUsuarioEmpleado(),
                    empleado.getCodRol()});

            }

        } else {

            for (Empleado empleado : regEmp.buscarPorFiltro(condicion, txtBusqueda)) {
                java.sql.Date dateSql = new java.sql.Date(empleado.getFechaNacEmpleado().getDay(), empleado.getFechaNacEmpleado().getMonth(), empleado.getFechaNacEmpleado().getYear());
                modelo.addRow(new Object[]{empleado.getNumRutEmpleado(),
                    empleado.getDvRutEmpleado(),
                    empleado.getpNombreEmpleado(),
                    empleado.getpApellidoEmpleado(),
                    empleado.getsApellidoEmpleado(),
                    empleado.getEmailEmpleado(),
                    empleado.getCelularEmpleado(),
                    dateSql,
                    empleado.getDireccionEmpleado(),
                    empleado.getCodComuna(),
                    empleado.getCodProvincia(),
                    empleado.getCodRegion(),
                    empleado.getUsuarioEmpleado(),
                    empleado.getCodRol()});

            }
        }

    }//GEN-LAST:event_jbttn_buscarFiltroActionPerformed

    private void jbtn_buscarRut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarRut1ActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        String rut = jtxt_rutBuscado2.getText();
        Empleado empleado = regEmp.buscarEmpleado(rut);

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_busquedaResultado.getModel();
        modelo.setRowCount(0);

        java.sql.Date dateSql = new java.sql.Date(empleado.getFechaNacEmpleado().getDay(), empleado.getFechaNacEmpleado().getMonth(), empleado.getFechaNacEmpleado().getYear());
        modelo.addRow(new Object[]{empleado.getNumRutEmpleado(),
            empleado.getDvRutEmpleado(),
            empleado.getpNombreEmpleado(),
            empleado.getpApellidoEmpleado(),
            empleado.getsApellidoEmpleado(),
            empleado.getEmailEmpleado(),
            empleado.getCelularEmpleado(),
            dateSql,
            empleado.getDireccionEmpleado(),
            empleado.getCodComuna(),
            empleado.getCodProvincia(),
            empleado.getCodRegion(),
            empleado.getUsuarioEmpleado(),
            empleado.getCodRol()});


    }//GEN-LAST:event_jbtn_buscarRut1ActionPerformed

    private void jtxt_rutBuscado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rutBuscado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rutBuscado2ActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        RegistroEmpleado regEmp = new RegistroEmpleado();
        String rut = jtxt_rutBuscado2.getText();
        
        regEmp.eliminarEmpleado(rut);
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_salir3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_gestionarEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_gestionarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtn_borrar;
    private javax.swing.JButton jbtn_borrar2;
    private javax.swing.JButton jbtn_buscarRut;
    private javax.swing.JButton jbtn_buscarRut1;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JButton jbtn_guardar2;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JButton jbtn_salir2;
    private javax.swing.JButton jbtn_salir3;
    private javax.swing.JButton jbtn_vistaAgregar;
    private javax.swing.JButton jbtn_vistaBuscar;
    private javax.swing.JButton jbtn_vistaEliminar;
    private javax.swing.JButton jbtn_vistaModificar;
    private javax.swing.JButton jbttn_buscarFiltro;
    private javax.swing.JCheckBox jchk_mostraContra;
    private javax.swing.JCheckBox jchk_mostraContra1;
    private javax.swing.JComboBox<String> jcmbo_comuna;
    private javax.swing.JComboBox<String> jcmbo_comuna2;
    private javax.swing.JComboBox<String> jcmbo_provincia;
    private javax.swing.JComboBox<String> jcmbo_provincia2;
    private javax.swing.JComboBox<String> jcmbo_region;
    private javax.swing.JComboBox<String> jcmbo_region2;
    private javax.swing.JComboBox<String> jcmbo_rol;
    private javax.swing.JComboBox<String> jcmbo_rol2;
    private com.toedter.calendar.JDateChooser jdate_fecNac;
    private com.toedter.calendar.JDateChooser jdate_fecNac2;
    private javax.swing.JRadioButton jrad_rol;
    private javax.swing.JRadioButton jrad_rut;
    private javax.swing.JRadioButton jrad_todos;
    private javax.swing.JTabbedPane jtabPane_gestionarEmpleado;
    private javax.swing.JTable jtbl_busquedaFiltro;
    private javax.swing.JTable jtbl_busquedaResultado;
    private javax.swing.JTextField jtxt_aMaterno;
    private javax.swing.JTextField jtxt_aMaterno2;
    private javax.swing.JTextField jtxt_aPaterno;
    private javax.swing.JTextField jtxt_aPaterno2;
    private javax.swing.JTextField jtxt_busqueda;
    private javax.swing.JTextField jtxt_celular;
    private javax.swing.JTextField jtxt_celular2;
    private javax.swing.JPasswordField jtxt_contraseña;
    private javax.swing.JPasswordField jtxt_contraseña2;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_direccion2;
    private javax.swing.JTextField jtxt_dvRut;
    private javax.swing.JTextField jtxt_dvRut2;
    private javax.swing.JTextField jtxt_mail;
    private javax.swing.JTextField jtxt_mail2;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_nombre2;
    private javax.swing.JTextField jtxt_numRut;
    private javax.swing.JTextField jtxt_numRut2;
    private javax.swing.JTextField jtxt_rutBuscado;
    private javax.swing.JTextField jtxt_rutBuscado2;
    private javax.swing.JTextField jtxt_usuario;
    private javax.swing.JTextField jtxt_usuario2;
    // End of variables declaration//GEN-END:variables
}
