/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author nearQ
 */
public class Form_MenuPpal extends javax.swing.JFrame {

    /**
     * Creates new form Form_MenuPpal
     */
    public Form_MenuPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmi_ingresarProducto = new javax.swing.JMenuItem();
        jmi_eliminarProducto = new javax.swing.JMenuItem();
        jmi_actualizarProducto = new javax.swing.JMenuItem();
        jmi_listarProducto = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenu();
        jbtn_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenu3.setText("Productos");

        jmi_ingresarProducto.setText("Ingresar");
        jmi_ingresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_ingresarProducto);

        jmi_eliminarProducto.setText("Eliminar");
        jmi_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_eliminarProducto);

        jmi_actualizarProducto.setText("Actualizar");
        jmi_actualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_actualizarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_actualizarProducto);

        jmi_listarProducto.setText("Listar");
        jmi_listarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_listarProducto);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jmi_salir.setText("Salir");

        jbtn_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });
        jmi_salir.add(jbtn_salir);

        jMenuBar1.add(jmi_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ingresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarProductoActionPerformed
        Form_ingresarProducto fip = new Form_ingresarProducto();
        fip.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarProductoActionPerformed

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void jmi_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarProductoActionPerformed
        Form_eliminarProducto fip = new Form_eliminarProducto();
        fip.setVisible(true);
    }//GEN-LAST:event_jmi_eliminarProductoActionPerformed

    private void jmi_actualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_actualizarProductoActionPerformed
        Form_actualizarProducto fip = new Form_actualizarProducto();
        fip.setVisible(true);
    }//GEN-LAST:event_jmi_actualizarProductoActionPerformed

    private void jmi_listarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarProductoActionPerformed
        Form_listarProducto fip = new Form_listarProducto();
        fip.setVisible(true);
    }//GEN-LAST:event_jmi_listarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MenuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jbtn_salir;
    private javax.swing.JMenuItem jmi_actualizarProducto;
    private javax.swing.JMenuItem jmi_eliminarProducto;
    private javax.swing.JMenuItem jmi_ingresarProducto;
    private javax.swing.JMenuItem jmi_listarProducto;
    private javax.swing.JMenu jmi_salir;
    // End of variables declaration//GEN-END:variables
}
